# Site settings
title: Portfolio
name: Rudi Pham
email: rudi@unstad.co
phone: +1 908 295 3165
description: Architectural & Interior designer from Norway, based in Brooklyn, NY.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/portfolio" # the base hostname & protocol for your site
twitter:
instagram: citizenpham
github: CitizenPham

# Let the viewers know if your available or not
hirable: true

# Build settings
markdown: kramdown

# Project collection
collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      type: projects
    values:
      path: ""
      layout: project

# Let's hide this please
exclude: ["_dev",
          "gulpfile.js",
          "node_modules",
          "package.json"]
