# Site settings
title: Portfolio
name: Rudi Pham
email: rudipham@me.com
phone: +1 908 295 3165
description: Architect
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://citizenpham.github.io/portfolio" # the base hostname & protocol for your site
twitter:
instagram: citizenpham
github: CitizenPham

# Let the viewers know if your available or not
hirable: true

# Build settings
markdown: kramdown

# Project collection
collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      type: projects
    values:
      path: ""
      layout: project

# Let's hide this please
exclude: ["_dev",
          "gulpfile.js",
          "node_modules",
          "package.json"]
